[package]
name = "fastShell"
version = "0.1.0"
authors = ["Christian Menges <christian.menges@tum.de>"]
edition = "2018"

[dependencies]
conch-parser = "0.1.0"
owned_chars = "0.3"
libc = "0.2"
clap = "~2.33"
postgres = "0.19.1"

[dev-dependencies]
proptest = "1.0.0"